{% set name = "pywis-topics" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 434fee92dd7ca83a9302eafb1166b107aa3e47b34265e594d373ed623e60e999

build:
  entry_points:
    - pywis-topics=pywis_topics:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click

test:
  imports:
    - pywis_topics
  commands:
    - pip check
    - pywis-topics --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wmo-im/pywis-topics
  summary: pywis-topics is a utility to work with the WIS2 Topic Hierarchy
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
